# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Sweet-More
version:      0.01
version_from: lib/Class/DBI/Sweet/More.pm
installdirs:  site
requires:
    Class::DBI::Sweet:             0.08
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
